#!/usr/bin/env sh





if [ -z "$CODA_FILEPATH" ]
then

	osascript -e "beep"
	exit

fi





/usr/bin/osascript <<-EOF

tell application "Terminal"

	activate
	do script "cd `dirname ${CODA_FILEPATH}`"

end tell

EOF

